### ISSUE TITLE
October 2022 Hybrid meeting agenda

### ISSUE THREAD

**Issue by dtig** [WebAssembly/meetings#1107]
What should we discuss at the next in-person (with virtual attendance options) meeting? Please use this issue to add items you would like to discuss, and are interested in hearing about.

**Comment by fgmccabe** [comment]
1. Would like to have a fiber switching session + vote
2. Would like to get a vote on JSPI

**Comment by conrad-watt** [comment]
Aiming to have a Threads to phase 3 vote (currently hacking away at the outstanding test suite requirements).

**Comment by tlively** [comment]
It would be good to do an update on GC progress since we entered phase 2. It's possible but unlikely that we'll be ready for a phase 3 vote. We'll know for sure closer to the meeting.

**Comment by ngzhian** [comment]
I can give an update on Relaxed SIMD, and potentially a poll for Phase 4.

**Comment by conrad-watt** [comment]
Hi all, I've begun a list of items to be scheduled across the two days https://github.com/WebAssembly/meetings/blob/main/main/2022/CG-10.md#items-to-be-assigned-slots

Anyone who's already proposed an item should suggest a tentative timebox and note any scheduling constraints. Anyone who would still like to propose an item can comment here or open a PR against the agenda linked above.

**Comment by titzer** [comment]
Can we add a logistical note to the page to put the Google office address (for those scheduling hotels)?

Thanks.

**Comment by titzer** [comment]
Also, I think we should have a slot devoted to talking about roadmap and strategy overall for Wasm. The format for the slot might be a panel or open discussion. Overall I'd like us to reestablish a shared sense of direction for the overall picture at a higher level than individual proposals.

**Comment by dtig** [comment]
@titzer, that sounds like a good idea. Do you have a structure, or some high level discussion points and a guess at a time allotment?

**Comment by titzer** [comment]
I think we should take at least 30 minutes and do it sort of like a round table.

A few key questions for discussion, off the top of my head:

1. Who do we see as the key stakeholders (not in the room) that can benefit from Wasm?
2. What are priorities for 2023 and beyond with Wasm?
3. How should we balance depth (e.g. better penetration into the Web platform) versus breadth (new platforms) of influence?
4. What are the good and bad parts of our process--what is working and what can be improved?
