### ISSUE TITLE
SIMD narrow / widen, min / max

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/meetings#111]
*Action item*: (not done from last meeting) JZ / BN to come back with concrete proposal of what the narrowing/widening, min/max operations should look like.

**Comment by dtig** [comment]
Closing this issue as [narrowing](https://github.com/WebAssembly/simd/blob/master/proposals/simd/SIMD.md#integer-to-integer-narrowing)/[widening](https://github.com/WebAssembly/simd/blob/master/proposals/simd/SIMD.md#integer-to-integer-widening) as well as the [min/max](https://github.com/WebAssembly/simd/blob/master/proposals/simd/SIMD.md#lane-wise-integer-minimum) operations are included in the current proposal.
