### ISSUE TITLE
Making "tailcall" part of the function signature

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/meetings#113]
*Action item*: Andreas to explore making “tailcall” part of function signatures, and document why he thinks this has bad implications. Michael / Luke to synchronize on why it would be useful to them.

**Comment by jfbastien** [comment]
At the Fastly in-person meeting we took the following poll:

POLL: We want to consider proceeding in a different direction than what Andreas has proposed, based on data that Michael will collect.

SF | F | N | A | SA
6 | 4 | 12 | 3 | 0

**Comment by fgmccabe** [comment]
Closing this, we have settled on not having special signatures for tail call functions.
