### ISSUE TITLE
Status of next in-person meeting

### ISSUE THREAD

**Issue by conrad-watt** [WebAssembly/meetings#1270]
Hi all, I had intended to give a short update on the status of the next in-person meeting during the 25/04 meeting, but since this was cancelled due to a thin agenda I will instead give an initial update here.

We had originally hoped to hold our next in-person/hybrid meeting in mid-July, in coordination with the Wasm Summit. Unfortunately this plan no longer seems viable, and so @dtig, @dschuff, and I are instead investigating the possibility of running our meeting as part of the W3C TPAC event in September, which is based in Spain (https://www.w3.org/2023/09/TPAC/). Some of you may remember that the Wasm CG attended a previous edition of TPAC back in 2018.

The upshot is that our next in-person CG meeting will take place in _September or later_. We will first investigate meeting through TPAC, and then investigate other European venues if TPAC is not viable.

**Comment by conrad-watt** [comment]
Closing now that initial details of the next in-person meeting have been announced, to be held in Google Munich in October.

**Comment by ttraenkler** [comment]
@conrad-watt Do you have any reference to information about the meeting e.g. specific dates?

**Comment by conrad-watt** [comment]
@dtig "pre-announced" [last week](https://github.com/WebAssembly/meetings/pull/1294/files) that we're aiming for 11-12th October.

**Comment by ttraenkler** [comment]
Thanks for the note, unfortunately these exact days I am on another conference

**Comment by conrad-watt** [comment]
Ah that's unfortunate. I'll follow up with you on this privately.

**Comment by justinmichaud** [comment]
Is there any timeline for when this will be officially confirmed, and we can start booking travel?

**Comment by dtig** [comment]
I've added a document [here](https://github.com/WebAssembly/meetings/blob/main/main/2023/CG-10.md) with the confirmed dates, and location.

**Comment by fgmccabe** [comment]
Can we be more precise about the venue. Is it Google Germany GMBH, Erika-Mann-Straße, Munich, Germany, or Google Office Munich HOF, Munich, Germany?

**Comment by dtig** [comment]
The street address is in the doc as well under the "Location" bullet point, it is the one on Erika-Mann-Straße.

**Comment by fgmccabe** [comment]
Thanks
