### ISSUE TITLE
Future meetings?

### ISSUE THREAD

**Issue by matsbror** [WebAssembly/meetings#1406]
Sorry for maybe a stupid question. Is there a list of dates and times for future CG meetings?

**Comment by tomayac** [comment]
All planned meetings are listed in [WebAssembly/meetings/tree/main/main/2023](https://github.com/WebAssembly/meetings/tree/main/main/2023). The suffix is `-MM-DD`, or just `-MM` for multi-day meetings.

**Comment by matsbror** [comment]
But there is nothing after the meetings already held. Oct-10 which was held the last week is the last. But I will infer from last meetings which seemed to happen every other Tuesday at 16 UTC.

**Comment by marcokuoni** [comment]
I think this is the source you are looking for: https://www.w3.org/groups/cg/webassembly/calendar/

**Comment by matsbror** [comment]
Indeed

**Comment by dschuff** [comment]
The regular schedule is indeed every other Tuesday. The "source of truth" is the meetings repo; we usually add future meetings with empty templates in batches; if a meeting is missing from the repo it probably just means there is no agenda yet. We usually cancel meetings if there is no agenda 24 hours ahead (and there will be a PR/commit reflecting that in the repo when the cancellation happens). There is also a Google Calendar event that I can add you to. Any changes/cancellations are basically always reflected in the repo and Google Calendar, but not always in the W3C calendar.
