### ISSUE TITLE
Repurposing GC subgroup meeting slot for threads discussion

### ISSUE THREAD

**Issue by tlively** [WebAssembly/meetings#1438]
I anticipate that we will soon want a dedicated forum for discussing the details of shared-everything-threads. Since the GC subgroup is not actively discussing anything right now, it makes sense to reuse their meeting slot for threads. The meeting slot is at the same time as the normal CG meeting on alternate weeks.

 1. Would that meeting slot work for folks interested in shared-everything-threads?

 2. Procedurally, do we need to charter a new subgroup for this?

**Comment by rossberg** [comment]
Repurposing the meeting slot sounds good to me, but I think we'll need a different subgroup and charter for it. As @conrad-watt pointed out yesterday as well, the basic problem it intends to tackle is independent of any GC feature. And the scope currently defined in the GC charter is entirely disjoint. It would be more appropriate to form a new subgroup (and put the GC subgroup on hiatus).

**Comment by tlively** [comment]
I've proposed a charter for a new threads subgroup here: https://github.com/WebAssembly/shared-everything-threads/pull/21

**Comment by tlively** [comment]
I've also opened a PR to discuss the proposed charter in the CG on December 5. If anyone would be interested in co-chairing the new subgroup, please chime in [here](https://github.com/WebAssembly/shared-everything-threads/pull/21#issuecomment-1827056931).

**Comment by tlively** [comment]
The threads subgroup is now up and running using the meeting slot as proposed.
