### ISSUE TITLE
Minutes for WASI 2023-12-14 meeting?

### ISSUE THREAD

**Issue by jeffparsons** [WebAssembly/meetings#1456]
Were minutes taken for the last WASI meeting (preview 2 discussion / Q&A)?

**Comment by jeffparsons** [comment]
@pchickey / @ricochet: Do you recall who, if anybody, took minutes for this meeting? Any chance they could be made public before the Jan 11 meeting? 🙏

**Comment by pchickey** [comment]
Sorry for the delay, I missed this before winter break, they are posted now: https://github.com/WebAssembly/meetings/pull/1459
