### ISSUE TITLE
Branch protections for meetings main branch?

### ISSUE THREAD

**Issue by tlively** [WebAssembly/meetings#1542]
Right now it is possible to push commits directly to the main branch of this repo. To improve visibility of changes and avoid mistaken direct pushes, I suggest that we change the branch protections to disallow direct pushes and require opening PRs instead. Most of the commits to this repo already go through PRs, but some do not, so this change would affect some people's workflows.

What would folks think of making this change?

cc @fgmccabe and @ricochet, since your workflows would be affected.

**Comment by fgmccabe** [comment]
Mixed opinion: normally I also use the PR approach. But, I just now pushed a change directly: that one was canceling our upcoming meeting. 
I don't think that that kind of change should go through a review process.

**Comment by fitzgen** [comment]
Making a PR to cancel meetings can be nice because people might see the PR email but have missed the calendar event's email.

**Comment by tlively** [comment]
To be clear, I think it's totally fine to create a PR and then immediately merge it without review if appropriate. As @fitzgen said, the email notification that generates is still useful.

**Comment by ricochet** [comment]
I am totally onboard with protecting the main branch with requiring a PR. My workflow is to open a PR first. There was one case where I opted to make an edit that I didn't need/want to trigger a notification, but protecting main is a greater priority than that edge case.

**Comment by tlively** [comment]
I've gone ahead and added the branch protection rule requiring PRs to modify the main branch. I'll close this issue, but if anyone runs into trouble with this, feel free to open a new issue.
