### ISSUE TITLE
Update spec tests to not be polymorphic

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/meetings#155]
From CG-01-26:

Some of the tests import a module called `spectest` and import a function called `print` which is overloaded by the embedder. Each import re-imports it with a different signature, but that’s weird because WebAssembly itself doesn’t have overloading. That way you could implement the `spectest` module in WebAssembly. Same with kinds: a global and function could have the same name.

* Andreas: we could remove it from core tests, but we should still make sure that it validates.
* Luke: I like the principle of being able to implement standard library in WebAssembly.
* Andreas: I would propose removing the print function from the spec tests. We should use assertions instead. It’s no longer relevant. We’ll still test imports, but it doesn’t have to be print.

*POLL:* unanimous consent to remove polymorphic imports.

*AI:* Dan to update spec tests to not be polymorphic.

**Comment by rossberg** [comment]
Refers to WebAssembly/spec#650, PR is in progress at WebAssembly/spec#652.

**Comment by binji** [comment]
This change landed; closing.
