### ISSUE TITLE
Videoconferences should support WebRTC-capable browsers

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/meetings#157]
CG and WG videoconference meetings are currently hosted with Google Hangouts. When I attempt to attend meetings with Firefox, I'm presented with a page which says:

> For some web browsers, including Firefox, Hangouts uses a plugin to enable video and phone calls.

> Firefox is ending support for plugins, so Hangouts won’t be able to support video and phone calls in Firefox until Hangouts is updated to resolve the problem. Google is working on a solution that will be available as soon as possible.

To reflect the spirit of cross-browser collaboration and Web standards, the WebAssembly videoconference meetings should support WebRTC-capable browsers.

**Comment by eholk** [comment]
Do you have suggestions for systems to consider instead?

**Comment by lukewagner** [comment]
IIUC, Google Hangouts works with WebRTC, just not when the meeting is created with the internal Google reservation system.  E.g., if I schedule something with meet.google.com, it works with WebRTC.

**Comment by jfbastien** [comment]
<img width="412" alt="screen shot 2018-02-01 at 14 17 05" src="https://user-images.githubusercontent.com/298127/35706445-99d2f16a-075a-11e8-8547-474758ba9fbe.png">

🤔

**Comment by littledan** [comment]
In Igalia, we use Jitsi for meetings, which works on Chrome and Firefox for me; I have not tested other browsers. We could use the Igalia Jitsi instance if you'd like, with a room at https://jitsi.igalia.com/WebAssemblyCG

**Comment by jfbastien** [comment]
On Safari:

<img width="706" alt="screen shot 2018-02-06 at 10 03 42" src="https://user-images.githubusercontent.com/298127/35875731-0a59ce18-0b25-11e8-8ac1-20f6a0c47e1c.png">

:sad:

**Comment by fideltian** [comment]
zoom.us

**Comment by jfbastien** [comment]
We hit Hangout's 30 person limit today. This is a problem. @linclark and Pat mentioned that zoom.us works well for them as well. Let's give it a try next time.

**Comment by rrwinterton** [comment]
This is a workaround and not a solution but we could use an audio bridge for those that do not present and are not concerned about video?  I think I can provide an audio bridge for people to use.
