### ISSUE TITLE
February 2025 Hybrid Meeting dates

### ISSUE THREAD

**Issue by lukewagner** [WebAssembly/meetings#1680]
As mentioned in the CG meeting [today](https://github.com/WebAssembly/meetings/blob/main/main/2024/CG-10-22.md), we're tentatively planning to host the next in-person/hybrid CG + Research Day meeting in the Fastly SF offices on February 11-13.

Although we unfortunately won't be able to resolve them all, please post if there are significant scheduling conflicts.  Thus far, we're working with the goal of meeting February and avoiding known scheduling conflicts in the first and last weeks of February.

**Comment by lukewagner** [comment]
Alright, looks like we're good to go with these dates (with February 11th being Research Day), so I'll close this issue.  [Here's](https://docs.google.com/forms/d/1tGz_47jPDCFCzHRvQEnNxbJru4Kg1AUApxwAeyX--AQ) the form that everyone wanting to attend in-person should fill out.  I'll also add an agenda item to the next CG meeting to share.

**Comment by dschuff** [comment]
Oops, the link you just posted seems to be the one from last October instead of February.

**Comment by lukewagner** [comment]
Hah, I just noticed that too, thanks.  Fixed, and I'll update the agenda item too.  [Here's](https://docs.google.com/forms/d/e/1FAIpQLSei-6h9luzk71GDHYi6avRftA5SyQOgL31mJIBu1BJ2Vhh0og/viewform?usp=sf_link) the new link.
