### ISSUE TITLE
Create CG sub-groups

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/meetings#191]
From https://github.com/WebAssembly/meetings/blob/master/2018/CG-03-20v21.md

Would CG subcommitees be useful for some topics like:

* Exceptions
* ES6 Modules
* CSP

Do we need anything formal or would informal work?

We’re getting bigger features. Would it make sense to have optional CG meetings for people interested in these particular topics?

*AI*: JF to check with W3C what the process is, CC Brad and Eric Prud'hommeaux.

Do we want mailing lists? How do we organize? GitHub issues? Video chats? Sub-group chair (should those be the champions)? How do we establish charter for sub-groups? Notes, timing, other requirements?

**Comment by jfbastien** [comment]
I contacted team-community-process@w3.org and Eric.

They're not aware of other CGs doing this, and don't see any issue with us doing so.

I'll put this on the agenda for the in-person meeting, where we'll see what people think.

**Comment by xtuc** [comment]
I know that TC39 has subgroups, but not sure it's something formal.

**Comment by jfbastien** [comment]
> I know that TC39 has subgroups, but not sure it's something formal.

Right it wouldn't be a new CG or anything like that. I'm thinking separate repos (which we already have), a champion (which we also have), and separate mailing lists + video calls (neither of which we have). That allows people who are interested to participate or lurk, without spamming 1000 CG members.

I like the division that [the C++ committee has](https://isocpp.org/std/the-committee) and I think it works well: it allows focused independent work, and them bubbles decision up to the wider group.

**Comment by xtuc** [comment]
I agree (but I won't be able to vote for that at the next meeting).

I guess that's what working groups are for?

**Comment by lukewagner** [comment]
I think a "GC" subcommittee would also be valuable.

**Comment by jfbastien** [comment]
> I guess that's what working groups are for?

Not in [the process we've adopted](https://github.com/WebAssembly/meetings/blob/master/process/phases.md) for WebAssembly: the WG is the last step in getting an official standard, whereas the CG adds all the new features and tries out all the wild things, purposefully culling some out over time.

If you've familiar with the C++ committee, the CG is EWG / LEWG, whereas the WG is CWG / LWG. The sub-groups being proposed are all the SGs, and they report to EWG / LEWG, never directly to CWG / LWG.

**Comment by eholk** [comment]
I don't know that we need anything super formal here (and I don't think anything proposed so far crosses into "too formal"). I imagined subcommittee VCs would be basically the same as our normal video call, but with an agenda focused on a specific proposal where we can go into a bit more depth. For example, in exception handling we might do an issue triage meeting to make sure we've addressed all the issues we need to. Any CG member would be welcome at any of these, but the idea is to have a focused meeting that people who aren't interested in the guts of a subject could feel free to skip.

At the all-CG calls, periodically a representative from a subcommittee could give a status update. I imagine in many cases we'd only need to present to the larger group when seeking phase advancement.

**Comment by xtuc** [comment]
Could we add this to the next meeting https://github.com/WebAssembly/meetings/blob/master/2018/CG-04-03.md?

Also we could already find out in what people are interested about.

**Comment by jfbastien** [comment]
Done: https://github.com/WebAssembly/meetings/pull/193

**Comment by littledan** [comment]
The TC39 subgroups are completely informal. We don't even have them organized as official Ecma Ad-Hoc Task Groups. These are just places for us to talk technical issues where we take some notes. All official technical decisions are discussed in the plenary. For now, this structure is sort of necessary, since we're at the size where there are a number of people who need to be consulted on every big decision.

I've heard that, in some standards committees, due to subcommittees being able to make strong independent decisions, some organizations need to make sure that they have someone in each room at all times; I don't think WebAssembly or TC39 need to be at this sort of level of maturity yet.

**Comment by dtig** [comment]
Closing this as we have several functional CG subgroups.
