### ISSUE TITLE
WebAssembly in Blockchains

### ISSUE THREAD

**Issue by sinahab** [WebAssembly/meetings#206]
WebAssembly is finding a home within blockchains.

As a non-web platform, blockchains have distinct requirements. We have compiled notes from projects across the space ([Ethereum](https://www.ethereum.org/), [Parity](https://www.parity.io/), [Dfinity](https://dfinity.org/), and [Truebit](https://truebit.io/)), and will use this session to give an overview of approaches and challenges to the wider community. Referenced in [CG-04](https://github.com/sinahab/meetings/blob/master/2018/CG-04.md).

We will discuss the following points:

* An overview of the blockchain VM:
  * A coordination layer between the WebAssembly VM and blockchain state.

* The blockchain VM needs to be deterministic (for nodes to reach consensus within the distributed network):
  * Resource limits: stack depth & memory.
  * Floating point.
  * Other sources of indeterminism: instantiation of a module

* Blockchains meter resource utilization:
  * The mechanics of metering: insert metering instructions per branch after verification.
  * Time: metering for instructions
  * Space: metering for memory

* Typed traps
  * To enable symbolic execution and static analysis tools.

* Imports
  * Accessing the memory: a spec for non-browser-based VMs.
  * Async / promises.
  * Having a WebAssembly standard library which defines operating system syscall.

* Instrumentation:
  * Two parts: 1) what to collect, 2) how to collect it.
  * Introducing ways to inspect the stack.

* Backward compatibility
  * Good: WASM binaries starts with a distinct flag.
  * Existing projects: JULIA, evm2wasm.

* New WASM developments which will be helpful:
  * Multi-values
  * References types
  * Annotations
  * Capabilities

* New WASM developments which might not be helpful (due to non-determinism):
  * Threads (with shared memory).
  * GC
  * SIMD.

**Comment by aj07** [comment]
@sinahab did you had meeting on it? When will be the next meeting. I want to be part of it.

**Comment by lrettig** [comment]
@sinahab any interest in planning one of these for 2019?

**Comment by sinahab** [comment]
@lrettig – happy to help, though will probably not have the capacity to be the primary driver. What are you thinking?

**Comment by lrettig** [comment]
Did this happen last year? If so, are there any notes or recordings?

**Comment by binji** [comment]
Here are the meeting notes and slides from the April 2018 meeting: https://github.com/WebAssembly/meetings/blob/master/2018/CG-04.md#webassembly-in-blockchain

**Comment by lrettig** [comment]
Thanks @binji, this is awesome and very helpful.

Several of us are hoping/planning to attend [CG-06](https://github.com/WebAssembly/meetings/blob/master/2019/CG-06.md) including @recmo, @axic, maybe @sinahab? I wonder if we don't have some interesting findings from the past year of work on Ethereum and related projects to share.

**Comment by binji** [comment]
@lrettig Sounds good! Feel free to send a PR to that document w/ with an agenda item, and who wants to lead the discussion. We haven't really started planning that meeting yet, so things may end up moving around a bit.
