### ISSUE TITLE
HTML serialization of WebAssembly.Module objects

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/meetings#209]
At the [2018-04-03 meeting](https://github.com/WebAssembly/meetings/blob/master/2018/CG-04-03.md) Dan presented his findings. After a long discussion we concluded:

*AI*: Dan to come back with update next meeting.

**Comment by littledan** [comment]
Posted a summary in https://github.com/WebAssembly/spec/pull/711#issuecomment-380573692 .
