### ISSUE TITLE
Page for tracking proposal state?

### ISSUE THREAD

**Issue by lars-t-hansen** [WebAssembly/meetings#212]
I'm filing this here because this is the repo in which the 'process' document lives.

Do we have a page that tracks proposals and the stage that each proposal is at?

I was going to propose that the CG meeting this week advance the sign extension opcodes proposal but to my distress I'm unable to find out even what stage it is at now, much less whether we are tracking in a systematic way whether any entrance criteria are met for the next stage.

For TC39 it seems to be the case that something is a proposal iff it is on the proposals list, and that list is relatively easy to find.  If we have such a thing for Wasm we should make it easier to find it.  If we don't have one we should make one.

**Comment by lars-t-hansen** [comment]
I now see that we have little badges on the individual README.md documents in the proposal repos to signify the current proposal state.  (Sign extension ops are stage 3.)

I also see that @binji is the keeper of an issue that attempts to track work items for the next stage (https://github.com/WebAssembly/sign-extension-ops/issues/2).

I still think it would be a good idea to centralize some of this information, and to structure it in a way that is more easily comprehensible.  Having to scan the issue and collect information to find this out is not quite ideal.

**Comment by jfbastien** [comment]
We have: https://github.com/WebAssembly/design/blob/master/FutureFeatures.md
As well as: https://github.com/WebAssembly/design/issues?q=is%3Aissue+is%3Aopen+label%3A%22🛤+tracking%22

**Comment by lars-t-hansen** [comment]
@jfbastien, Thanks, that's helpful.

So do people feel that this is a sufficient level of tracking (and the champion / owner gets to keep track of when a feature can advance and make sure it does) or is it useful to discuss whether we should have a little more structure around that tracking, such as a visible checklist for the next phase on the front page of the repo's README?

**Comment by binji** [comment]
> such as a visible checklist for the next phase on the front page of the repo's README

I like this idea.

**Comment by jfbastien** [comment]
I would rather link to https://github.com/WebAssembly/meetings/blob/master/process/phases.md (which the tracking issues do) instead, because it prevents the checklist from becoming stale.

**Comment by binji** [comment]
We ended up creating https://github.com/WebAssembly/proposals for this purpose. Closing!
