### ISSUE TITLE
SIMD: usefulness of 8-bit multiply

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/meetings#231]
During [the SIMD discussion at Fastly](https://github.com/WebAssembly/meetings/blob/master/2018/CG-04.md#simd) we took the following action item:

  Action Item: Dan Gohman to do research into the usefulness of 8-bit multiply.

**Comment by dtig** [comment]
Closing this issue as the 8-bit multiply is no longer a part of the [current SIMD proposal](https://github.com/WebAssembly/simd/blob/master/proposals/simd/SIMD.md#integer-multiplication).
