### ISSUE TITLE
Concern re procedure for changing stable draft specs

### ISSUE THREAD

**Issue by lars-t-hansen** [WebAssembly/meetings#234]
The PR https://github.com/WebAssembly/mutable-global/pull/13 incompatibly changes the JS API in the mutable-globals spec, to wit, a value that was previously in the globals descriptor is now passed as a second parameter to the constructor.  I don't really object to the technical matter here, but to how this change was made to a spec that has been stable for some time.  The change is mentioned twice, very briefly, in the meeting notes and appears to be a fallout from discussion about reference types; there was no poll re making the change (unlike, say, changing the default value for FP globals); the PR itself contains no justification for its existence, not even a reference to the minutes or to an Issue.

Not everyone working on wasm can attend all the CG meetings, sadly, but that seems immaterial.  Changes of this kind to fairly stable features need better supporting materials and need to be backed by a poll.

**Comment by binji** [comment]
Sorry, this is my fault. I mentioned it brielfy [here](https://github.com/WebAssembly/mutable-global/issues/6#issuecomment-382849520), but should have written a better commit message and pinged you in the message as well. As for the poll, I seem to recall asking for an informal poll of the room about this. But I should have asked for an official poll instead.

**Comment by jfbastien** [comment]
I thought that we'd polled it as well, apologies! @binji could you add a poll to the next video call?

**Comment by binji** [comment]
Done: https://github.com/WebAssembly/meetings/pull/235

**Comment by lars-t-hansen** [comment]
Thanks, that's great.  I'll likely miss the meeting (May 1 holiday) but I've no technical objection to the change, FWIW.

**Comment by binji** [comment]
We discussed this in the [May 1st CG meeting](https://github.com/WebAssembly/meetings/blob/master/2018/CG-05-01.md#webassemblyglobal-constructor) and decided that `WebAssembly.Global` should take its initial value as a second argument.

As mentioned above, we will make sure to have polls for changes like these in the future.
