### ISSUE TITLE
When will SIMD be released? It is the most important feature i think.

### ISSUE THREAD

**Issue by fideltian** [WebAssembly/meetings#267]

**Comment by dtig** [comment]
Fixed-width SIMD is still in the [Feature proposal stage](https://github.com/WebAssembly/meetings/blob/master/process/phases.md#1-feature-proposal-community-group), with prototype implementations of the [current design](https://github.com/WebAssembly/simd/blob/master/proposals/simd/SIMD.md) in some embedders. What use cases for SIMD are you interested in?

**Comment by fideltian** [comment]
video processing on browser. The performance is not good without SIMD

**Comment by fideltian** [comment]
https://webrtchacks.com/zoom-avoids-using-webrtc/ 
The article is interesting.

**Comment by dtig** [comment]
- closing this issue as this has had follow up in SIMD meetings, and offline.
