### ISSUE TITLE
CG meeting calendar events are wrong

### ISSUE THREAD

**Issue by xtuc** [WebAssembly/meetings#275]
It seems that I just missed a WebAssembly CG meeting today at 4pm-5pm UTC, in my calendar the event is tomorrow at 8 am GMT+2.

I don't know if i'm the only one but the recurring event seems to be in a wrong timezone.

**Comment by jayphelps** [comment]
FWIW mine is correct (I’m in eastern time). I use both Google Calendar synced with Apple calendar.

**Comment by binji** [comment]
No, that doesn't seem right. The CG meetings should always be on a Tuesday. And my calendar event still has the full hour...

**Comment by xtuc** [comment]
Ok, how does that work? Are you sending calendar events each time or is it a shared calendar?

I can setup my own recurring event for CG meetings for now.
