### ISSUE TITLE
TPAC dates seems wrong

### ISSUE THREAD

**Issue by xtuc** [WebAssembly/meetings#306]
cc @binji @littledan 

In https://github.com/WebAssembly/meetings/blob/945dab8924f81131300c7e193c901810ed1edd4d/2018/TPAC.md, the dates are:
- Thursday 25th - 10:00am to 5:00pm (GC)
- Friday 26th - 10:00am to 5:00pm (GC)

On their website (https://www.w3.org/2018/10/TPAC/schedule.html), the dates are:
- Tuesday 23th - 10:30 - 12:30 (GC)
- Thursday 25th - entire day? (WG)
- Friday 26th - entire day? (WG)

One person from TPAC/W3C confirmed those dates to me. If we all agree on these dates, I can submit a PR to correct the TPAC.md file.

---

Also personnally I'd like to participate in the meetings (espically for ESM if scheduled). Given those dates and being only in the GC, spending my time to be in Lyon for 2 hours seems a bit "overkilled" to me. I suppose that very few peoples from GC will show up.

**Comment by binji** [comment]
I've added a clarification to the `TPAC.md` here: https://github.com/WebAssembly/meetings/pull/307

**Comment by xtuc** [comment]
Are you sure that the info are wrong on their website? They did confirm me the same dates (today). Should I forward you the discussion?

**Comment by binji** [comment]
Yes, I've been in discussion with them. Technically the dates are correct, but we are using the rooms for the Working Group for the Community Group instead.
