### ISSUE TITLE
WG meetings for CG observers

### ISSUE THREAD

**Issue by chicoxyzzy** [WebAssembly/meetings#339]
From WG agendas:

> If you are a Community Group member who would like to observe, please register here: https://goo.gl/forms/HD2kLCM0iSKk7AVl1

I've tried to fill this form 5 times since August but never got a response. How to get a link to observe WG meetings?

**Comment by binji** [comment]
TBH, I don't know where this form goes. @jfbastien is it sent to you?

**Comment by jfbastien** [comment]
That was Brad.

**Comment by bashor** [comment]
I also failed to get an invitation a few times.

cc @lukewagner @dschuff

**Comment by bashor** [comment]
Finally, I got the invitation. Thank you, @chicoxyzzy, and others who were involved!

**Comment by dschuff** [comment]
Sorry about this. Apparently the form wasn't configured to notify anyone when it was submitted 🤦 I've fixed that.
