### ISSUE TITLE
June 2019 Meeting Agenda

### ISSUE THREAD

**Issue by binji** [WebAssembly/meetings#398]
What topics shall we cover at the meeting? Comment below and I'll add/remove them from this list.

All times are currently estimates. If you think a topic needs more time, please comment below.

- [WebIDL bindings](https://github.com/WebAssembly/proposals/issues/8) (1-2 hrs)
- [Garbage Collection](https://github.com/WebAssembly/proposals/issues/16) (1 hr?)
  - Split [typed imports](https://github.com/WebAssembly/gc/blob/master/proposals/gc/MVP.md#imports) and [exports](https://github.com/WebAssembly/gc/blob/master/proposals/gc/MVP.md#exports) out from GC proposal
- [Threads](https://github.com/WebAssembly/proposals/issues/14) (1 hr)
  - [Add fence instruction](https://github.com/WebAssembly/tool-conventions/issues/59#issuecomment-490268705) (½ hr)
- [ECMAScript Module Integration](https://github.com/WebAssembly/proposals/issues/12) (1 hr)
  - Exported function to call after instantiation (see https://github.com/WebAssembly/design/issues/1160#issuecomment-495373810)
- [Exception Handling](https://github.com/WebAssembly/proposals/issues/4) (½-1 hr)
- JS/web adjacent topics: (1 hr)
  -  WeakRefs, Atomics.waitAsync, built-in modules, import-maps, WebIDL, get-originals
- [SIMD](https://github.com/WebAssembly/proposals/issues/1) (½-1 hr)
- [Reference Types](https://github.com/WebAssembly/proposals/issues/10) (½-1 hr)
- [Function references](https://github.com/WebAssembly/proposals/issues/39) (½-1 hr)
- [Bulk Memory](https://github.com/WebAssembly/proposals/issues/18) (½ hr)
  - Passive element segment encoding
- Collaborative benchmark suite (½ hr)
- [Multi Value](https://github.com/WebAssembly/proposals/issues/19) (update) (¼-½ hr)
  - Poll: phase 4
- [Tail Calls](https://github.com/WebAssembly/proposals/issues/17) (¼ hr)
- [Debugging Subgroup topics?](https://github.com/WebAssembly/debugging) (?)
  - Separable debug info
  - Source maps
- [C/C++ API](https://github.com/WebAssembly/proposals/issues/24) (drop?)
- ~~[WASI topics?](https://github.com/WebAssembly/wasi)~~

**Comment by rossberg** [comment]
* Function references
* Reference types (update)

**Comment by binji** [comment]
@lukewagner @lars-t-hansen @aheejin @littledan @sunfishcode @dschuff @tschneidereit @linclark @dtig

**Comment by littledan** [comment]
I'm curious if folks would be interested in quick status updates in various adjacent JS/web features under development (e.g., WeakRefs, Atomics.waitAsync, built-in modules, import-maps, WebIDL, get-originals). These are being designed with Wasm in mind, but I am not sure how visible the big picture is. If it would be useful, I would be happy to present on some of these, but I am also happy to leave the time free for other topics.

**Comment by dtig** [comment]
An agenda item on SIMD sounds good, a few of us have been working on SIMD mostly outside of the regular CG meetings, so I'd like to report back with updates.

**Comment by KronicDeth** [comment]
Elixir/Erlang would be interested in

* Threads
* Garbage Collection
* Tail Calls

**Comment by littledan** [comment]
For threads, should we discuss the effort from @annevk and others to get the right HTTP headers worked out to permit reliable process isolation across browsers? I believe this is what's blocking Wasm threads in some browsers.

**Comment by binji** [comment]
@littledan we can mention it, but I wonder if there's much to discuss in the context of this meeting.

**Comment by lars-t-hansen** [comment]
I'm mostly interested in (a) improving wasm for the web platform and (b) adding to wasm's performance features.  So WebIDL, reference types + function references, ES module integration, SIMD, threads, and exception handling are probably the high-value topics for me.

**Comment by dschuff** [comment]
For threads, we should consider the idea discussed [here](https://github.com/WebAssembly/tool-conventions/issues/59#issuecomment-490268705)  of adding a fence instruction for better forward compatibility with future relaxed atomics.

**Comment by tlively** [comment]
It would be great to have 15-30 minutes for a status update on multivalue as well. I don't think there's much to discuss, but we've some recent work on the tools and it would be good to update the community on our progress.

**Comment by binji** [comment]
We discussed this a little in the May 28 CG meeting. It sounds like we'd like to give significant time to WebIDL bindings, Threads, Exception Handling. Speaking to @dtig, we may not need much time for SIMD, perhaps just a half hour.

I think we'll want to have WebIDL discussion near the end of the day (in the range 3-5pm GMT+2, 6-8am PDT)  to accommodate PDT timezone folks. We may want to try to do the same for SIMD. @fgmccabe @rrwinterton does that work for you?

We probably shouldn't discuss WASI, as many of the subgroup members will not be at the meeting. We may want to discuss Debugging, though if we do I'd like to have some concrete topics. @dschuff, thoughts?

**Comment by binji** [comment]
I've added some time estimates as well, please comment if you think a topic needs more or less time.

**Comment by KronicDeth** [comment]
> We may want to discuss Debugging, though if we do I'd like to have some concrete topics.

* Separable debug-info, so we can ship `wasm-strip`'d `.wasm` file, but then load up the stripped debug info such as function names when we need to debug in the browser.
* Source maps (standardize on a custom section?) for the original language
  * Maybe come up with a protocol to allow highlighting those source maps for the original language

**Comment by littledan** [comment]
Half an hour seems like enough for the JS/web-adjacent topics. If we are short on time, I would be fine to reduce it to 15 minutes or just hallway track.

**Comment by rossberg** [comment]
@kmiller68, what's the current status of multi values in JSC? At the autumn meeting you mentioned it was almost done. If there has been enough progress and no issues arose then we could discuss moving the proposal to stage 4 at the meeting.

**Comment by lars-t-hansen** [comment]
Function references will take more time than the proposed 30min, if we're going to go into any depth at all.

Technically passive element segments belong to bulk memory, not reference types?  (Indeed bulk memory is still at stage 3 and we can do pretty much what we want with that proposal.)

It's been quiet on the GC front lately (at least in public), so 2hrs seems high, time might be better spent on other near-term features.

**Comment by titzer** [comment]
I'd like to add an agenda item to discuss a collaborative benchmark suite.

**Comment by titzer** [comment]
+1 to moving multi values to stage 4. The V8 implementation has been done for some time, and we've been itching to ship it :)

**Comment by lukewagner** [comment]
Overall looking good.  A few requests/ideas:
* I think it'd be nice to have an explicit agenda item under ESM-integration for [this issue](https://github.com/WebAssembly/design/issues/1160) and the proposed solution.
* I think JS/web-adjacent topics could usefully fill an hour.  Probably good to juxtapose or join with ESM-integration and Web IDL Bindings since they all fit into the same interconnected Web story for wasm.
* A useful GC sub- or replacement-topic that we could make concrete progress on would be to discuss a new proposal that factors out [type imports](https://github.com/WebAssembly/gc/blob/master/proposals/gc/MVP.md#imports) (and [exports](https://github.com/WebAssembly/gc/blob/master/proposals/gc/MVP.md#exports)) of the GC proposal (similar to what we've already done with reference-types and function-references).  This could be our next step toward the grand GC future that enables Web IDL Bindings and WASI [use cases](https://github.com/WebAssembly/webidl-bindings/blob/master/proposals/webidl-bindings/Explainer.md#open-questions)).

**Comment by binji** [comment]
OK, I've updated the top comment w/ new times and additional agenda items based on your comments. Assuming the maximum time on each, we're at 11.5 hrs not including debugging, which is about right.

**Comment by binji** [comment]
I've written up the agenda in the meeting doc here, PTAL! https://github.com/WebAssembly/meetings/pull/412
