### ISSUE TITLE
Recording Of June Meeting?

### ISSUE THREAD

**Issue by Warfields** [WebAssembly/meetings#429]
Are there recordings of the presentations given earlier this month? Specifically [This presentation](https://docs.google.com/presentation/d/1edgPUudnvIGM6I9veoCTb6bmsfNYoqHogFAEExUJchw/edit#slide=id.p)?

**Comment by binji** [comment]
Sorry, we don't record the meetings. Was there a specific question you had about the slides? Perhaps @littledan can explain.

**Comment by littledan** [comment]
Thanks for your interest in this topic, and sorry about the lack of recording. Happy to answer any questions here over the next week.

**Comment by Warfields** [comment]
Ok I'll get some questions!

**Comment by Warfields** [comment]
@littledan my only question is what would be the best way to help contribute to moving the proposal forward? (IE work on the [prototype work](https://docs.google.com/presentation/d/1wtAknL-UJWDoIgSbyF5paTBSpVVj-fKU4tiHMxJbSzE/edit#slide=id.g5b10a6dc5c_19_77)

**Comment by littledan** [comment]
@Warfields Probably best to ask in an issue on that repo--are you talking about https://github.com/jgravelle-google/wasm-webidl-polyfill ? I think there's also work to do in Emscripten to integrate with WebIDL bindings, but it may already be ongoing and in good shape; you can get in touch with that project at https://github.com/emscripten-core/emscripten . cc @jgravelle-google

**Comment by Warfields** [comment]
> @Warfields Probably best to ask in an issue on that repo--are you talking about https://github.com/jgravelle-google/wasm-webidl-polyfill ? I think there's also work to do in Emscripten to integrate with WebIDL bindings, but it may already be ongoing; you can get in touch with that project at https://github.com/emscripten-core/emscripten . cc @jgravelle-google

More generally moving the WebIDL proposal from [phase 2 to phase 3](https://github.com/WebAssembly/meetings/blob/master/process/phases.md#2-proposed-spec-text-available-community--working-group). From my understanding this involves two items. First, one or more prototype implementations, like [Rust IDL](https://github.com/rustwasm/wasm-webidl-bindings) and the [wasm-webidl-polyfill ](https://github.com/jgravelle-google/wasm-webidl-polyfill) prototypes. Secondly, the testing framework.

In retrospect it's probably better to open an issue on [the proposal](https://github.com/WebAssembly/webidl-bindings) on where it'd be best for me to help out on the proposal.
