### ISSUE TITLE
Extended name section repo

### ISSUE THREAD

**Issue by AndrewScheidecker** [WebAssembly/meetings#434]
During the 7/9 video call, the CG consented to advancing my [extended name section proposal](https://github.com/AndrewScheidecker/wasm-extended-name-section/) to phase 1.

Can somebody with access please create a repo for it under the WebAssembly org?

**Comment by binji** [comment]
Sure, @dschuff can you do it?

**Comment by dschuff** [comment]
Done, https://github.com/WebAssembly/extended-name-section
