### ISSUE TITLE
WebAssembly at TPAC 2019

### ISSUE THREAD

**Issue by dtig** [WebAssembly/meetings#435]
[TPAC 2019](https://www.w3.org/2019/09/TPAC/Overview.html) is coming up on the 16–20 of  September. Starting this as a coordination issue for folks that plan to attend TPAC. In previous meetings when we discussed TPAC, there was consensus on not having a CG meeting this time, but interest in using this as an opportunity to interact with other community/working groups. There was also interest in hosting a WebAssembly AMA as was done last year. Some notes - 

- The WebAssembly CG does not have a reserved room at TPAC this time, but there is a room set aside for the Wasm WG on Thursday, 9/19 that we may be able to use. If folks going would like a dedicated room, please reply to this and I can follow up to see if this can be arranged.
- The plenary day (9/18) may be a good time to host the Wasm AMA

Even if you don't intend to attend TPAC in person, please take a look at the [schedule](https://www.w3.org/2019/09/TPAC/schedule.html) and respond with issues that may be useful to discuss there.

**Comment by grassel** [comment]
I can not find WebAssembly on the TPAC schedule page. What's the plan about WASM at TPAC ?
Please clarify, I should make my travel plans.

**Comment by tidoust** [comment]
@dontcallmedom and I are proposing a TPAC breakout session on [efficient audio/video processing](https://www.w3.org/wiki/TPAC/2019/SessionIdeas#Efficient_audio.2Fvideo_processing) to discuss use cases that rely on media processing one way or the other, such as barcode reading, face/gesture tracking, emotion analysis, funny hats, background removal or blurring, augmented reality, video overlays, voice effects, or custom codecs. Goal is to determine whether there is a good common mechanism that different APIs could leverage to hook with media streams efficiently.

This could typically include discussion on ways to allow WebAssembly, a good candidate to implement some of the use cases, to access encoded and/or raw media. WASM experts and feedback welcome!

**Comment by dtig** [comment]
If the breakout session takes place, notes would be appreciated for those of us not able to attend.
