### ISSUE TITLE
Ensure that meeting times correctly take DST into account

### ISSUE THREAD

**Issue by Ms2ger** [WebAssembly/meetings#465]
[Today's meeting](https://github.com/WebAssembly/meetings/blob/master/2019/CG-11-12.md#agenda-for-the-november-12th-video-call-of-webassemblys-community-group) claims to be at November 12th, 4pm-5pm UTC (November 12th, 9am-10am Pacific Daylight Time), but DST is no longer in effect in the Pacific time zone.

**Comment by xtuc** [comment]
Is 4pm-5pm UTC still correct? It's supposed to be now

**Comment by dschuff** [comment]
The time listed on the md doc didn't match the time in Calendar/Zoom. Sorry about that.

**Comment by xtuc** [comment]
Is there a way to get invite to the calendar invite again?

**Comment by Ms2ger** [comment]
Yeah, "Send an email to the acting [WebAssembly CG chair](mailto:webassembly-cg-chair@chromium.org)".

If this meeting is supposed to be pinned to Pacific time, perhaps that should be listed first, though.

**Comment by dschuff** [comment]
Yeah, you're probably right. I'll try to get that right for future meetings (since the md files often get copy/pasted from one week to the next, hopefully one week of remembering that will be enough).
