### ISSUE TITLE
Please announce meeting cancellations

### ISSUE THREAD

**Issue by Ms2ger** [WebAssembly/meetings#468]
Even around Thanksgiving.

**Comment by tlively** [comment]
FWIW the cancellation was mentioned at the last meeting, but wider announcements would of course be good.

**Comment by Ms2ger** [comment]
I was wondering about that, so I checked the meeting notes at #466 and… nothing.

**Comment by dschuff** [comment]
Yeah, sorry about that.
We also cancelled the calendar invite with plenty of advance notice, but of course not everyone is directly subscribed to that system either. I'll try to do better next time.
