### ISSUE TITLE
February 2020 in-person meeting agenda

### ISSUE THREAD

**Issue by dtig** [WebAssembly/meetings#474]
What should we discuss at the next in-person meeting? Please comment with agenda items, or things we should discuss so these can be added to the agenda. 

I've added some items, and estimated times. Suggestions to remove, or edit time estimates also appreciated. 

- [Garbage Collection](https://github.com/WebAssembly/gc) (2 Hr)
- [Interface Types](https://github.com/WebAssembly/interface-types) (1 - 1½ Hr)
- [Fixed-Width SIMD](https://github.com/webassembly/simd) (½ Hr)
- [Exception Handling](https://github.com/WebAssembly/exception-handling) (½ Hr)
- Stack switching / Coroutines / Effect handlers (½ - 1 Hr)
- [Feature Detection](https://github.com/WebAssembly/feature-detection) (½ Hr)
- [Type Reflection for WebAssembly JavaScript API](https://github.com/WebAssembly/js-types) (½ Hr)
- [Multiple Memories](https://github.com/WebAssembly/multi-memory) (½ - 1 Hr)
- [Typed Function References](https://github.com/WebAssembly/function-references/issues) (½ - 1 Hr)
- [Bulk Memory Operations](https://github.com/WebAssembly/bulk-memory-operations) (½ - 1 Hr)
  - Poll to Phase 4? 
- [Reference Types](https://github.com/WebAssembly/reference-types) (½ - 1 Hr)
  - https://github.com/WebAssembly/reference-types/issues/76
  - Poll to Phase 4?
- [Tail calls](https://github.com/WebAssembly/tail-call) (¼ - ½ Hr)
  - Poll to phase 4?
- Debugging topics
  - Limitations of Source maps
- WASI topics (1½ Hr)
  - [WASI Embedding API](https://github.com/WebAssembly/WASI/issues/149), Interface Types and WASI
  - WASI security model, reference types, interface types, and POSIX
- [CT-Wasm](https://github.com/PLSysSec/ct-wasm) (¼ - ½ Hr)
- [Custom Annotation Syntax in the Text Format](https://github.com/WebAssembly/annotations) (¼ - ½ Hr)

**Comment by tlively** [comment]
I'm happy to only spend half an hour on feature detection. I think 10 minutes for an update and 20 minutes for discussion seems reasonable.

**Comment by lars-t-hansen** [comment]
Reference types to phase 4 is on my Christmas wishlist, too.  The main blocker seems to be https://github.com/WebAssembly/reference-types/issues/31 (last comment): getting declared segments into the spec & interpreter.  And then at least one more implementation needs to implement that + nullref.  So it's possible pushing for phase 4 is premature, but I'd like to explore the possibility.

**Comment by dtig** [comment]
Thanks @tlively and @lars-t-hansen - I've added an item for reference types, and updated time required for feature detection.

**Comment by ErikMcClure** [comment]
I would be interested in discussing the current state of debugging support and limitations regarding Source Maps I encountered while attempting to implement pass-through C++ debugging support in an AoT compiler.

**Comment by dtig** [comment]
@rossberg @lukewagner @aheejin @tschneidereit @binji @dschuff @sunfishcode 

Does the time for discussions seem reasonable? Are there other things we should discuss?

**Comment by aheejin** [comment]
Not sure we need 1.5 hrs for EH. 1 hr will be probably sufficient, if not too long. I'm also planning to advance the proposal to phase 2, but haven't decided if we are gonna do it before the in-person CG meeting or not.

**Comment by peterhuene** [comment]
I would like to propose a discussion on the [C embedding API](https://github.com/WebAssembly/wasm-c-api) (or as separate extensions that layer on top of the C API) regarding interface types and WASI.

Topics regarding interface types:
* Checking for support of interface types in the engine.
* Getting interface-types-based import and export signatures for a module.
* Instantiating a module with interface-types-based imports where the engine handles the adapter logic.
* How to handle host string encodings.
* Is it desirable to have an API to describe the interface types custom section for custom embeddings?
* Where does this API live (as part of the current C API or as a layered extension)?

Topics regarding WASI ([see this issue for more context](https://github.com/WebAssembly/WASI/issues/149)):
* Checking for support of a WASI implementation in the engine (alternatively: how to gracefully handle unsupported WASI versions vs. confusing import binding errors).
* Configuring the engine's WASI implementation (preopens, rights, etc.).
* Instantiating a module with imports from the engine's WASI implementation.
* Sharing WASI instances between different module instantiations.
* Where should the API live (e.g. a WebAssembly c-wasi-api repo)?

I think 45 minutes will suffice for this. I'll have API proposals ready to present to kickstart design discussion.

**Comment by deian** [comment]
If there is room, I would love to talk about  Constant-Time WebAssembly ([CT-Wasm](https://github.com/PLSysSec/ct-wasm)) and more broadly why and how we can extend Wasm to  allow developers to safely write cryptographic algorithms in Wasm. Frank Denis already wrote up a nice and concise summary of why we need this: https://github.com/WebAssembly/WASI/issues/65#issuecomment-510780981.

This topic was brought up before by others: https://github.com/WebAssembly/design/issues/1299 https://github.com/WebAssembly/WASI/issues/65 https://github.com/denoland/deno/issues/3097

**Comment by rossberg** [comment]
Sorry for being slow to reply.

I suspect that we will need more time for a discussion on GC to make sense (2 hours or more). I want to test the room for some back-to-the-drawing-board ideas around the central issue of casts that might be fairly technical and take time to digest.

If there is room, I'd also be happy to present preliminary ideas for stack switching / coroutines / effect handlers, since I have mentioned them and being asked about them on a number of occasions and feel bad about not having provided a more "official" intro and pointer yet. (1/2-1 hour)

**Comment by rossberg** [comment]
Oh, and given that it's heavily used by interface types, we should probably discuss the annotations proposal again. (1/4-1/2 hour)

**Comment by aheejin** [comment]
> Not sure we need 1.5 hrs for EH. 1 hr will be probably sufficient, if not too long. I'm also planning to advance the proposal to phase 2, but haven't decided if we are gonna do it before the in-person CG meeting or not.

I think we are going to vote on the phase advancement in the meeting. And come to think of it, even including the vote, I don't think we need a full hour, unless we revisit previous discussions. I think 0.5 hrs should be sufficient, or people can have a long break :)

**Comment by dtig** [comment]
Thanks everyone, I've updated the issue and will shortly be formulating this into a more formal agenda. Please continue to use this issue to propose other topics if any. If you have scheduling constraints and would like to be present for a session, submit a PR to [CG-02.md](https://github.com/WebAssembly/meetings/blob/master/2020/CG-02.md) so that any constraints can be taken into account while allocating time slots.

**Comment by paolosevMSFT** [comment]
The link for "Debugging topics" should probably be https://github.com/WebAssembly/debugging/issues.

**Comment by binji** [comment]
Deepti added the agenda here: https://github.com/WebAssembly/meetings/blob/master/2020/CG-02.md#agenda-items

Please take a look and see if the order works for you. As always, we'll likely be moving things around up to (and including) the days of the meeting. :-)

**Comment by sunfishcode** [comment]
In the WASI section, I'd like to propose a presentation, covering the WASI security model, the anticipated relationships with reference types and interface types, and the relationship to POSIX.

Seperately, CT-WASM shouldn't be a sub-item of WASI, since it's a core language feature that isn't specific to WASI.

**Comment by dtig** [comment]
Thanks @sunfishcode, I've moved CT-WASM out from WASI topics. Could you also provide a time estimate for the proposed presentation?

**Comment by deian** [comment]
For CT-Wasm 1/4-1/2 should work

**Comment by sunfishcode** [comment]
@dtig For the WASI presentation, I estimate a half hour.

**Comment by dtig** [comment]
@lars-t-hansen Looks like https://github.com/WebAssembly/reference-types/issues/31 is now closed, is there more there that may need discussion? If not I can take it off the agenda.

**Comment by binji** [comment]
There's a related topic here that we may want to discuss if it isn't resolved by then: https://github.com/WebAssembly/reference-types/issues/76

**Comment by lars-t-hansen** [comment]
> @lars-t-hansen Looks like [WebAssembly/reference-types#31](https://github.com/WebAssembly/reference-types/issues/31) is now closed, is there more there that may need discussion? If not I can take it off the agenda.

@dtig, you can take it off the agenda.

**Comment by chicoxyzzy** [comment]
Would it be possible to attend remotely?

**Comment by KronicDeth** [comment]
I’d be interested in remote too. I had too many conferences this month to also make the meeting.

**Comment by dtig** [comment]
Attending remotely is possible, [email](mailto:webassembly-cg-chair@chromium) for the calendar link. Just a caveat though, that given the size of the group this time it's possible that all the discussion may not come through over VC, but all the presentations should work well.

**Comment by binji** [comment]
Thanks for a great meeting everyone!
