### ISSUE TITLE
Feb CG in-person meeting notes

### ISSUE THREAD

**Issue by billti** [WebAssembly/meetings#509]
Will the meeting notes be published? I see the page at <https://github.com/WebAssembly/meetings/blob/master/2020/CG-02.md> has a spot _"to be populated after the meeting"_.

I couldn't stay for the face-to-face, but based on proposal and design repo movement, looks like some interesting discussions and progress happened I'd like to get an overview of if possible.

**Comment by dtig** [comment]
Just opened the PR to add meeting notes here in https://github.com/WebAssembly/meetings/pull/510. Should be merged soon!
