### ISSUE TITLE
Off cadence meeting to discuss subtyping

### ISSUE THREAD

**Issue by dtig** [WebAssembly/meetings#529]
A quick follow up from the CG meeting earlier, we decided to have an off cadence meeting to discuss https://github.com/WebAssembly/reference-types/issues/69. This has been discussed a few times over the last couple of months and as we haven't reached a decision, setting up this meeting as a space exclusively space for this discussion. 

If you would like to contribute to the discussion, please fill out this [form](https://forms.gle/FipvfshbVfhX11Hb9). No action necessary if you would like to observe, this meeting will be added to your calendar if you are a regular attendee to the CG meeting. 

Cc: @rossberg @RossTate @lukewagner @binji

**Comment by RossTate** [comment]
Thanks, @dtig! The times are listed in PST, but California is now in PDT. Should we interpret them as PDT?

**Comment by RossTate** [comment]
Cool. I've filled it out. If need be, I can probably make the 8am PDT meeting times too, but it requires checking if my partner can shuffle around our work/toddler-watching rotation. So just let me know if I should look into that.

**Comment by dtig** [comment]
I've added as many slots as possible to have the meeting within the week, so we can continue the discussion without it getting stale, I'll update here as soon as some subset of folks have responded. Will reach out individually if we need to schedule it at a time that's not marked as favorable in the responses.

**Comment by rossberg** [comment]
We should definitely try to do it this week, since I won't be unavailable the next due to surgery.

The Friday slot is way into the weekend on the European end, would there be an earlier time perhaps?

**Comment by dtig** [comment]
Thanks to everyone who responded, we should be able to do this tomorrow. Looks like most people are available at Thursday April 2nd, 9:00AM - 10:00AM PDT (6:00PM - 7:00PM CET), will schedule this as soon as I've heard back from a couple of outliers.

**Comment by dtig** [comment]
At the previous [meeting](https://github.com/WebAssembly/meetings/blob/master/2020/CG-04-02-Subtyping.md), we concluded that we need another off cadence meeting to continue this discussion.

Adding a [form](https://forms.gle/N8zTN6teyrkVmMCM9) here to schedule the follow up meeting with a range of available time slots, please fill out this form to participate in the discussion. Also note that this is in addition to the existing CG meeting on 2/14/20 next week.

**Comment by RossTate** [comment]
Thanks for organizing! I filled out the form, but I also wanted to let you know that you should bug me if it would help for me to make the 8am PDT times. If so, I can check if my spouse can shuffle their schedule a bit.

**Comment by dtig** [comment]
The follow up meeting for this is scheduled now for Tuesday, April 21st, 10:00AM - 11:00AM PDT (7:00PM - 8:00PM CET). This is later than usual for CET, but is the only time all of the required attendees are available.
