### ISSUE TITLE
Please add notes of April 14th meeting

### ISSUE THREAD

**Issue by sabine** [WebAssembly/meetings#551]
I'm trying to follow the reasoning for and against the recently proposed anyref funcref change. Tried to look up notes from April 14th and they aren't in yet. Please add, if possible.

**Comment by dtig** [comment]
I'll be adding notes shortly, but I'm assuming you're looking for discussion on this https://github.com/WebAssembly/reference-types/issues/69, and this proposed change https://github.com/WebAssembly/reference-types/pull/87, most of this discussion has happened in prior meetings, and not in this meeting.

Here are the previous meetings where this was discussed, including off-cadence meetings specifically scheduled for this. 
 - [02/20 in-person meeting](https://github.com/WebAssembly/meetings/blob/master/2020/CG-02.md)
 - [03/31/20 meeting](https://github.com/WebAssembly/meetings/blob/master/2020/CG-03-31.md)
 - [04/02/20 meeting](https://github.com/WebAssembly/meetings/blob/master/2020/CG-04-02-Subtyping.md)
 - [04/28/20 meeting](https://github.com/WebAssembly/meetings/blob/master/2020/CG-04-28.md)

The last meeting has linked slides that also outline the for and against that you may be looking for.  Is this the information you are looking for? If so, the latest meeting only had the poll, and unfortunately not much time for discussion.

**Comment by sabine** [comment]
Thanks very much!
I wasn't sure if there was something in 4-14 on that as well.

**Comment by dtig** [comment]
No problem, there wasn't time for anything else on 4-14. But if you have concerns, or have other points for discussion please add it on the agenda for an upcoming meeting.
