### ISSUE TITLE
When does a Poll need lead time at CG video meetings?

### ISSUE THREAD

**Issue by dtig** [WebAssembly/meetings#581]
This was brought up by @fgmccabe today, when does a poll need lead time at CG video meetings? 

Recently after feedback that folks would like to be prepared ahead of time to take a poll, we've tried to stick to polling only when the poll was added to the agenda at least 24 hours before the start of the meeting. It was brought up today that this requirement should be relaxed for non-contentious polls, or minor proposal changes that require a poll. 

I suggest sticking to the existing requirements for polls as it's easier for attendees to prepare ahead of time when the polls are explicit, especially as there are discussions happening in different proposals and it may be hard to keep track of all of them at the same time. Opening this issue for an offline discussion ahead of the next meeting.

**Comment by binji** [comment]
I agree for most polls, but like @tlively I think perhaps we could make an exception for phase 1 polls (AFAIK we've never had any objections to phase 1 proposals). That said, we could also just remember to add a poll to the agenda for topics that we intend to go for phase 1.

**Comment by tlively** [comment]
When newcomers bring proposals to the CG I think they often do not expect to be ready for phase 1 after a single presentation or they don't know that votes have to be explicit in the agenda. I believe that's what happened with @echamudi's excellent proposal this morning. Part of the reason to make an exception for votes on preproposals is to remove an early stumbling block for new contributors and give them a more welcoming and streamlined experience.

**Comment by binji** [comment]
True, although that was my mistake too, I might have noticed before merging #568.

**Comment by fgmccabe** [comment]
My question was actually a bit different. I can see that creating a stage 1 proposal may need a poll of the CG. But, a small change in the specification itself? 
We could use some guidelines on what action(s) need a poll of the CG.

**Comment by binji** [comment]
> But, a small change in the specification itself? We could use some guidelines on what action(s) need a poll of the CG.

Yeah, this has come up a few times -- I think in this case it makes sense to bring to the CG since the reference types proposal is so far along. For smaller issues in early proposals, I'd assume the champion would make changes and mention to the CG in an update later.

**Comment by tlively** [comment]
There is pretty good high-level guidance at https://github.com/WebAssembly/meetings/blob/master/process/consensus.md#online-consensus:

> When a proposal is near maturity the champion shall bring it to an in-person meeting and seek wider consensus on open design points and contended issues.
