### ISSUE TITLE
Time-boxing agenda items

### ISSUE THREAD

**Issue by taralx** [WebAssembly/meetings#592]
It seems to me that most meetings run out of time regularly, resulting in later items on the agenda being bumped. Instead of doing that, what do people think about assigning agenda items a time limit, around 10-20 minutes? If an item runs out of time we either take it back up at the end if time permits or next meeting otherwise.

**Comment by binji** [comment]
I agree, and I like this idea. Let's try this out for the next meeting's topics. @tlively, can you give some estimates on your items?

**Comment by RossTate** [comment]
A complementary suggestion is to order agenda items so that more open-ended items happen after more procedural items.

**Comment by binji** [comment]
@RossTate agreed, though procedural items like polls often require some discussion before, which may need time boxing anyway.

**Comment by rossberg** [comment]
I'm in favour of time boxing as well. But we'll also need some mechanism by which to allocate an agenda item that requires more time. Not all topics can reasonably be discussed in 15 minutes.

My suggestion would be for each proposed agenda item to include an estimated time, and then adhere to that. Once the hour is full (perhaps leaving a 10 minute buffer), no more items can be accepted. It is up to the discretion of the chairs to reject PRs that want to grab unreasonable time slots.

**Comment by tlively** [comment]
I really liked the time boxing, and I say that as someone who was leading multiple discussions that got cut off in this morning's meeting. We were able to get to many more agenda items and get many more ideas in front of the CG with time boxing in effect, and followup discussion can still happen on GitHub.

**Comment by taralx** [comment]
It should come as no surprise that I liked the timeboxing. :)

**Comment by fitzgen** [comment]
I thought it worked well.

**Comment by binji** [comment]
OK, let's continue to do this for future meetings.

**Comment by tlively** [comment]
Timeboxing seems to be successful in making sure that all the scheduled items happen. I think the next step is to carve out time explicitly for discussions after presentations.
