### ISSUE TITLE
Polling for interest: Long-form virtual CG meeting

### ISSUE THREAD

**Issue by dtig** [WebAssembly/meetings#740]
It's been a year+ since the last in-person CG meeting, opening this issue to poll for interest to have a long-form virtual CG meeting as in person meetings will not be feasible for at least a few more months. As the current CG meeting agendas have started to fill up ahead of time, it may be worthwhile to meet for a longer duration, and the feedback we've had in the past is that the high level updates of the various proposals tend to be useful too. 

The tentative format would be 4Hr slots spread over 4 days in place of the in-person meeting which usually spans 2-2.5 days, with optional breakout meeting spaces. This issue is polling for interest if such a meeting was to be organized. It is possible that it may be challenging to plan around time zones, but it might be worth trying if there is enough interest. 

Filing this issue to poll for interest - a simple 👍 👎 reaction works to indicate interest. Ideas, alternatives, and longer form feedback also appreciated.

**Comment by fgmccabe** [comment]
👍
To clarify, are you suggesting 4x4hr slots?
I think that it may be easier to handle shorter time slots.

**Comment by dtig** [comment]
> To clarify, are you suggesting 4x4hr slots?

That is my current suggestion, inspired from how TC39, and other previously in-person events. This is very tentative at this point, so depending on interest/logistics if shorter time slots make most sense then that is what we would schedule.

**Comment by RossTate** [comment]
I've found that, for Zoom, more shorter times is better than fewer longer times, to the point that people just seem too zoned out after even a couple hours for the meeting to be that productive. So my personal preference would be 2 (or 3) hours a day, possibly 5 days, even if that means shortening the time until the next long-form meeting. That might also help keep the meeting within more accessible times with respect to timezone differences. But I know full well there's a lot to planning these meetings, so I'm happy to adjust to whatever facilitates planning 😃

**Comment by fgmccabe** [comment]
A back-of-the-envelope calculation suggests that one week of 2 hour meetings does not equal one face-to-face meeting. However, it is still better than not having one at all!

**Comment by dtig** [comment]
Closing this as no longer relevant, as there's a longer meeting scheduled [later this month](https://github.com/WebAssembly/meetings/blob/main/main/2022/CG-10.md), and I expect that we'll resume these meetings at some regular cadence in the future.
